name: Renovate

on:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/renovate-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: ./renovate.json
